---

- name: Install distro packages
  package:
    name: "{{ craton_distro_packages }}"
    state: latest

- name: Install pip packages
  pip:
    name: "{{ item }}"
    executable: pip3
    state: latest
  with_items:
    - "{{ craton_pip_packages }}"

- name: Install craton into venv
  pip:
    name: git+https://github.com/openstack/craton.git#egg=craton
    virtualenv: "/opt/craton-venv"
    virtualenv_python: python3.5
