---

- name: Checkout craton
  git:
    repo: https://github.com/openstack/craton.git
    dest: "{{ craton_root_dir }}"
    version: master
    force: true

- name: Build craton docker image
  docker_image:
    path: "{{ craton_root_dir }}"
    name: craton_api
    tag: latest

- name: Start craton docker image
  docker:
    name: craton_api
    state: started
    image: craton_api:latest
    ports: 0.0.0.0:7780:7780 
