---
- name: Install distro packages
  package:
    name: "{{ ecopoiesis_distro_packages }}"
    state: latest

- name: Install pip packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ ecopoiesis_pip_packages }}" 

- name: Create Ecopoiesis directories
  file:
    path: "{{ ecopoiesis_root_dir }}/{{ item }}"
    state: directory
  with_items:
    - configs
    - ipxe
    - EFI/x86

- name: Setup motd
  template:
    src: motd
    dest: /etc/motd

- name: Install DHCP Server Template
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
  notify: restart dhcp service

- name: Install Ecopoiesis iPXE Loader
  template:
    src: ecopoiesis.ipxe.j2
    dest: "{{ ecopoiesis_root_dir }}/ecopoiesis.ipxe"

- name: Install os_configs
  copy:
    src: os_configs/
    dest: "{{ ecopoiesis_root_dir }}/configs/"
    mode: 0444

- name: Install tftpd-hpa.conf
  copy:
    src: tftpd-hpa.conf
    dest: /etc/default/tftpd-hpa
  notify: restart tftpd-hpa service

- name: Remove default apache2 config
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent

- name: Install httpd miniplop config
  copy:
    src: plip.conf
    dest: /etc/apache2/sites-enabled/plip.conf

- name: Ensure images directory created
  file:
    path: "{{ ecopoiesis_root_dir }}/images/squashible-ubuntu-16.04-minimal"
    state: directory

- name: Retrieve ubuntu minimal live vmlinuz 
  get_url:
    url: http://images.squashible.com/images/ecopoiesis-utility/vmlinuz
    dest: "{{ ecopoiesis_root_dir }}/images/ecopoiesis-utility/vmlinuz"

- name: Retrieve ubuntu minimal live initrd
  get_url:
    url: http://images.squashible.com/images/ecopoiesis-utility/initrd.img
    dest: "{{ ecopoiesis_root_dir }}/images/ecopoiesis-utility/initrd.img"

- name: Retrieve ubuntu minimal live rootfs
  get_url:
    url: http://images.squashible.com/images/ecopoiesis-utility/rootfs.img
    dest: "{{ ecopoiesis_root_dir }}/images/ecopoiesis-utility/rootfs.img"
