---
- name: Install distro packages
  package:
    name: "{{ ecopoiesis_distro_packages }}"
    state: latest

- name: Create Ecopoiesis directories
  file:
    path: "{{ ecopoiesis_root_dir }}/{{ item }}"
    state: directory
  with_items:
    - configs
    - ipxe
    - EFI/x86

- name: Setup motd
  template:
    src: motd
    dest: /etc/motd

- name: Install DHCP Server Template
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
  notify: restart dhcp service

- name: Install Ecopoiesis iPXE Loader
  template:
    src: ecopoiesis.ipxe.j2
    dest: "{{ ecopoiesis_root_dir }}/ecopoiesis.ipxe"

- name: Install os_configs
  copy:
    src: os_configs/
    dest: "{{ ecopoiesis_root_dir }}/configs/"
    mode: 0444

- name: Checkout plip
  git:
    repo: https://github.com/antonym/plip.git
    dest: "{{ plip_root_dir }}"
    version: master
    force: yes

- name: Install plip config file
  template:
    src: plip_config.py.j2
    dest: "{{ plip_root_dir }}/config.py"
