---
- name: Install iPXE dependencies
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ ipxe_distro_packages }}"

- name: Checkout latest iPXE sources
  git:
    repo: "{{ ipxe_repo }}"
    dest: "{{ ipxe_source_dir }}"
    version: "{{ ipxe_branch }}"
    force: yes

- name: Copy iPXE embedded script to iPXE source directory
  template:
     src: ipxe-embed.j2
     dest: "{{ ipxe_source_dir }}/src/ipxe-embed"

- name: Touch iPXE config local files
  file:
    path: ""{{ ipxe_source_dir }}/src/config/local/{{ item }}"
    state: touch
  with_items:
  - console.h
  - umalloc.h
  - nap.h
  - timer.h
  - branding.h
  - serial.h
  - reboot.h
  - sanboot.h
  - fault.h
  - dhcp.h
  - sideband.h
  - entropy.h
  - crypto.h
  - usb.h
  - settings.h

- name: Compile iPXE disks
  shell: "make {{ item }} EMBED=ipxe-embed"
  with_items:
  - bin/ipxe.iso
  - bin/ipxe.lkrn
  - bin/ipxe.usb
  - bin/ipxe.dsk
  - bin/ipxe.pxe
  - bin/undionly.kpxe
  - bin-x86_64-efi/ipxe.efi
  args:
    chdir: "{{ ipxe_source_dir }}/src"


- name: Create iPXE file directory
  file:
    path: "{{ ecopoiesis_root_dir }}/ipxe"
    state: directory

- name: Copy iPXE files to http directory
  copy:
    src: "{{ ipxe_source_dir }}/src/bin/{{ item }}"
    dest: "{{ ecopoiesis_root_dir }}/ipxe/"
    remote_src: True
  with_items:
  - ipxe.iso
  - ipxe.lkrn
  - ipxe.usb
  - ipxe.dsk
  - ipxe.pxe
  - undionly.kpxe

- name: Copy EFI iPXE to directory
  copy:
    src: "{{ ipxe_source_dir }}/src/bin-x86_64-efi/{{ item }}"
    dest: "{{ ecopoiesis_root_dir }}/EFI/x86/"
    remote_src: True
  with_items:
  - ipxe.efi
