version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
        environment:
          - ENV: CI
    working_directory: ~/ecopoiesis

    steps:
     - run: |
         apt-get -qq update
         apt install -y git python-setuptools python-pip libssl-dev libffi-dev
         pip install ansible
     - checkout
     - run: |
         cd ~/ecopoiesis
         ansible-playbook -i localhost local.yml
