---

# default program locations
craton_bootstrap_config_file: /etc/craton/craton_bootstrap.cfg
craton_config_dir: /etc/craton
craton_log_dir: /var/log/craton
craton_root_dir: /opt/craton
ecopoiesis_root_dir: /opt/ecopoiesis 
plip_root_dir: /opt/plip

# plip configuration
craton_url: 'http://127.0.0.1:7780/v1'
craton_username: 'demo'
craton_password: 'demo'
craton_project_id: 'b9f10eca66ac4c279c139d01e65f96b4'

# craton database
craton_db_connection: localhost
craton_db_user: craton
craton_db_password: craton
craton_db_name: craton
