---

  - name: restart dhcp service
    service:
      name: "{{ dhcp_service }}"
      state: restarted
    ignore_errors: true

  - name: reload systemd
    command: systemctl daemon-reload

  - name: restart tftpd-hpa service
    service:
      name: "{{ tftpd_service }}"
      state: restarted
    ignore_errors: true
